name: Planned maintenance

description: Allow or deny branches based on the time and branch name

inputs:
  maintenance-window-start:
    description: "Time when the maintenance window will open.  After this point, the checklist will be enabled and the action will fail"
    required: true
  maintenance-window-duration:
    description: "Number of milliseconds the maintenance window will remain open for"
    required: true
  maintenance-url:
    description: "URL with more information about this maintenance, will be displayed in error output"
    required: false

outputs:
  message:
    description: "Explanation about why your branch was rejected"

runs:
  using: "node12"
  main: "index.js"
